# Generated by Django 3.2.14 on 2023-04-04 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_add_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='Contributor',
            new_name='contributor',
        ),
    ]
